# Generated by Django 4.0 on 2023-01-17 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0002_alter_user_groups_alter_user_user_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ordered_parts',
            fields=[
                ('op_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Parts',
            fields=[
                ('part_no', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('P_name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('car_manu', models.CharField(max_length=150)),
                ('car_name', models.CharField(max_length=150)),
                ('manufacture_year', models.CharField(max_length=10)),
                ('original', models.BooleanField()),
                ('desc', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SCP.categories')),
            ],
        ),
        migrations.CreateModel(
            name='Workshop_orders',
            fields=[
                ('wo_id', models.IntegerField(primary_key=True, serialize=False)),
                ('W_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Workshoporders', to='User.workshop')),
                ('op_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SCP.ordered_parts')),
            ],
        ),
        migrations.CreateModel(
            name='Workshop_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_field', models.ImageField(default='no-image.jpg', height_field='imageheight', upload_to='static/images/profile/20230117-195904', width_field='imagewidth')),
                ('imagewidth', models.PositiveIntegerField(default=50, editable=False)),
                ('imageheight', models.PositiveIntegerField(default=50, editable=False)),
                ('W_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='WorkshopImg', to='User.workshop')),
            ],
        ),
        migrations.CreateModel(
            name='Store_parts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Price', models.FloatField()),
                ('S_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='StoreParts', to='User.store')),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='SCP.parts')),
            ],
        ),
        migrations.CreateModel(
            name='Store_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_field', models.ImageField(default='no-image.jpg', height_field='imageheight', upload_to='images/part/20230117-195904', width_field='imagewidth')),
                ('imagewidth', models.PositiveIntegerField(default=50, editable=False)),
                ('imageheight', models.PositiveIntegerField(default=50, editable=False)),
                ('S_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='StoreInformation', to='User.store')),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('service_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=75)),
                ('W_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='WorkshopServices', to='User.workshop')),
            ],
        ),
        migrations.CreateModel(
            name='Part_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_field', models.ImageField(default='no-image.jpg', height_field='imageheight', upload_to='media/part_images/', width_field='imagewidth')),
                ('imagewidth', models.PositiveIntegerField(default=65, editable=False)),
                ('imageheight', models.PositiveIntegerField(default=65, editable=False)),
                ('P_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SCP.parts')),
            ],
        ),
        migrations.AddField(
            model_name='ordered_parts',
            name='sp_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='StoreParts', to='SCP.store_parts'),
        ),
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('offer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('offer_desc', models.CharField(max_length=200)),
                ('offer_price', models.IntegerField()),
                ('W_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='WorkshopOffers', to='User.workshop')),
                ('service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SCP.services')),
            ],
        ),
        migrations.CreateModel(
            name='Customer_orders',
            fields=[
                ('co_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Date', models.DateField()),
                ('C_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CustomerOders', to='User.customer')),
                ('S_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='StoreOders', to='User.store')),
                ('op_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SCP.ordered_parts')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Q', models.IntegerField(default=1)),
                ('C_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CustomerCart', to='User.customer')),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Cart', to='SCP.store_parts')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Time', models.TimeField()),
                ('C_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CustomerAppointment', to='User.workshop')),
                ('W_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='WorkshopAppointment', to='User.workshop')),
                ('service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SCP.services')),
            ],
        ),
    ]
