# Generated by Django 4.0 on 2023-01-02 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SCP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part_image',
            name='image_field',
            field=models.ImageField(default='no-image.jpg', height_field='imageheight', upload_to='static/images/profile/20230102-160748', width_field='imagewidth'),
        ),
        migrations.AlterField(
            model_name='store_image',
            name='image_field',
            field=models.ImageField(default='no-image.jpg', height_field='imageheight', upload_to='static/images/profile/20230102-160748', width_field='imagewidth'),
        ),
        migrations.AlterField(
            model_name='workshop_image',
            name='image_field',
            field=models.ImageField(default='no-image.jpg', height_field='imageheight', upload_to='static/images/profile/20230102-160748', width_field='imagewidth'),
        ),
    ]
