# Generated by Django 4.0 on 2023-02-16 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0001_initial'),
        ('SCP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop_orders',
            name='W_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Workshoporders', to='User.workshop'),
        ),
        migrations.AddField(
            model_name='workshop_orders',
            name='op_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SCP.ordered_parts'),
        ),
        migrations.AddField(
            model_name='workshop_image',
            name='W_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='WorkshopImg', to='User.workshop'),
        ),
        migrations.AddField(
            model_name='store_parts',
            name='S_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='StoreParts', to='User.store'),
        ),
        migrations.AddField(
            model_name='store_parts',
            name='p_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='SCP.parts'),
        ),
        migrations.AddField(
            model_name='store_image',
            name='S_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='StoreInformation', to='User.store'),
        ),
        migrations.AddField(
            model_name='services',
            name='W_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='WorkshopServices', to='User.workshop'),
        ),
        migrations.AddField(
            model_name='parts',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SCP.categories'),
        ),
        migrations.AddField(
            model_name='part_image',
            name='P_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SCP.parts'),
        ),
        migrations.AddField(
            model_name='ordered_parts',
            name='sp_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='StoreParts', to='SCP.store_parts'),
        ),
        migrations.AddField(
            model_name='offers',
            name='W_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='WorkshopOffers', to='User.workshop'),
        ),
        migrations.AddField(
            model_name='offers',
            name='service_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SCP.services'),
        ),
        migrations.AddField(
            model_name='customer_orders',
            name='C_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CustomerOders', to='User.customer'),
        ),
        migrations.AddField(
            model_name='customer_orders',
            name='S_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='StoreOders', to='User.store'),
        ),
        migrations.AddField(
            model_name='customer_orders',
            name='op_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SCP.ordered_parts'),
        ),
        migrations.AddField(
            model_name='cart',
            name='C_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CustomerCart', to='User.customer'),
        ),
        migrations.AddField(
            model_name='cart',
            name='p_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Cart', to='SCP.store_parts'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='C_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CustomerAppointment', to='User.customer'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='W_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='WorkshopAppointment', to='User.workshop'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='service_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SCP.services'),
        ),
    ]
