# Generated by Django 4.0 on 2023-02-15 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SCP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='image_field',
            field=models.ImageField(default='no-image.jpg', height_field='imageheight', upload_to='static/images/Services/20230215-232612', width_field='imagewidth'),
        ),
        migrations.AlterField(
            model_name='store_image',
            name='image_field',
            field=models.ImageField(default='no-image.jpg', height_field='imageheight', upload_to='images/part/20230215-232612', width_field='imagewidth'),
        ),
        migrations.AlterField(
            model_name='workshop_image',
            name='image_field',
            field=models.ImageField(default='no-image.jpg', height_field='imageheight', upload_to='static/images/profile/20230215-232612', width_field='imagewidth'),
        ),
    ]
