# Generated by Django 4.1.5 on 2023-01-16 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SCP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='Q',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='store_image',
            name='image_field',
            field=models.ImageField(default='no-image.jpg', height_field='imageheight', upload_to='images/part/20230116-002620', width_field='imagewidth'),
        ),
        migrations.AlterField(
            model_name='workshop_image',
            name='image_field',
            field=models.ImageField(default='no-image.jpg', height_field='imageheight', upload_to='static/images/profile/20230116-002620', width_field='imagewidth'),
        ),
    ]
