# Generated by Django 4.0 on 2023-01-02 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SCP', '0002_alter_part_image_image_field_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part_image',
            name='image_field',
            field=models.ImageField(default='no-image.jpg', height_field='imageheight', upload_to='static/images/profile/20230102-161036', width_field='imagewidth'),
        ),
        migrations.AlterField(
            model_name='store_image',
            name='image_field',
            field=models.ImageField(default='no-image.jpg', height_field='imageheight', upload_to='static/images/profile/20230102-161036', width_field='imagewidth'),
        ),
        migrations.AlterField(
            model_name='workshop_image',
            name='image_field',
            field=models.ImageField(default='no-image.jpg', height_field='imageheight', upload_to='static/images/profile/20230102-161036', width_field='imagewidth'),
        ),
    ]
