# Generated by Django 4.0 on 2023-02-16 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SCP', '0004_remove_dabrhaorders_order_no_dabrhaorders_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dabrhaorders',
            name='Request',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='store', to='SCP.dabrharequest'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='services',
            name='image_field',
            field=models.ImageField(default='no-image.jpg', height_field='imageheight', upload_to='static/images/Services/20230216-111412', width_field='imagewidth'),
        ),
        migrations.AlterField(
            model_name='store_image',
            name='image_field',
            field=models.ImageField(default='no-image.jpg', height_field='imageheight', upload_to='images/part/20230216-111412', width_field='imagewidth'),
        ),
        migrations.AlterField(
            model_name='workshop_image',
            name='image_field',
            field=models.ImageField(default='no-image.jpg', height_field='imageheight', upload_to='static/images/profile/20230216-111412', width_field='imagewidth'),
        ),
    ]
